### ISSUE TITLE
A few comments on the documentation 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/AutoDoc#100]
Just browsing the manual out of interest, and listing a few suggestions: 
2.2.12, 2.2.15    why give S5 the name S3? 
2.2.13, 2.2.14 (and elsewhere?)    "won't" not English - try "will not" 
2.2.13    "testet" -> "tested" 
2.2.15   starts off rather strangely: perhaps 'documentation' is being used in two different ways here?  Need to distinguish between text in a .gd file and the resulting manual. 
2.2.17   'programm'? 
2.7 intro:   "neither is strict" -> "neither is it strict"? 
2.7.1   "items lists" -> "lists of items",   "curse" -> "course" 
2.7.3   "asteriks" -> "asterisks" 
3.1.1   "sampe" -> "same",  "refer this command" -> "refer to this command" 
p.20, Mainpage   "hand written" -> "handwritten" 

Index:  
This is possibly how you want it, but it looks odd to have "AutoDoc, 4" and "AutoDoc, 18" in different places. 
No entry for makedoc.g

Chapter 4:  the AutoDoc() function is clearly a very complicated thing, and some sample examples of how it might be called would be very helpful. 

Help for people with existing GAPDoc  manuals:  there might be a new chapter/section giving guidance, e.g. warnings about overwriting existing files when trying makedoc.g for the first time. 
Section 1.3 is not sufficient here. 

Support for GAPDoc ENTITY construct?  This appears not to exist, which is why I am currently reluctant to experiment with AutoDoc any further.

**Comment by fingolfin** [comment]
Brilliant, thanks a lot for this feedback. We'll work on it.

**Comment by fingolfin** [comment]
The first index issue (with two entries "AutoDoc") was resolved by PR #99 (pure coincidence :-)

**Comment by fingolfin** [comment]
If I am not mistaken, after some recent fixes, the following three points remaing:

1. Add examples for using `AutoDoc()`.
2. Explain how to use AutoDoc in packages that already use GAPDoc, in more detail than Section 1.3.
3. Support GAPDoc entties.

Some comments on each:

1. For this, I just added a stub, examples still need to be written.
2. I fully agree, in fact I'd like to have a full chapter devoted for this. Some examples it should contain:
  * a minimal example how to use `AutoDoc()` to compile your manual, nothing else. 
  * some examples showing the `gapdoc` options.
  * an explanation how to use AutoDoc to generate a title page (nothing else)
  * examples for the fancier `scaffold` options
  * finally, how to use it for actual AutoDoc-style documentation comments.

3. Actually, this is already there, but not documented, because we were not sure if it is good as it is... We should change this (probably file a separate issue). For now, take a look at `gap/Magic.gd` and search for "entities". Or, indeed, look at the `makedoc.g` file of AutoDoc itself:
```
AutoDoc(rec( 
    autodoc := true,
    scaffold := rec(
        includes := [
            "Tutorials.xml",
            "Comments.xml"
            ],
        entities := [
            "SomePackage",
        ],
    )
));
```
This declares the entity `&SomePackage;`

**Comment by cdwensley** [comment]
Thanks - I'm now tempted to try it again, and let you know how the entities work out.

**Comment by sebasguts** [comment]
@cdwensley I looked at the definition of entities, and from what I can tell is that the ```entities``` parameter already offers (almost) all functionality except for an entity being plain text. Could you maybe point me to an example how you use it, since I am not sure I understand the GAPDoc documentation here completely.

**Comment by cdwensley** [comment]
Rather than respond to the previous comment, I prefer to try out the options offered in Magic.gd and then report back - but probably not today.

**Comment by fingolfin** [comment]
@cdwensley Thanks! Ideally, any reply should probably be on a new issue specific to entities handling (if you don't mind -- we'll read it either way :-)

**Comment by fingolfin** [comment]
@cdwensley I just made a new release, which has an improved manual; you can browse it here: http://gap-packages.github.io/AutoDoc/doc/chap0.html

If you have any further remarks, esp. on the new content: we are all ears ;-).

**Comment by cdwensley** [comment]
I will try to have a good look at this during the next few days but: 
(a)  a new version of Utils is needed before the Friday deadline because of new versions of RCWA and ResClasses released today; 
(b)  we might have to dash off for a week or so on grandparent duties at very short notice. 
Meanwhile, what is "More o" just before 1.4.2?

**Comment by fingolfin** [comment]
Closing this, as the remaining issues are tracked in #101, #102, #120
