### ISSUE TITLE
Feature request: treat a sequence empty autodoc comment as paragraph break

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#130]
I.e. imitate the behavior of MarkDown and LaTeX, so that this:
```gap
#! First paragraph.
#!
#! Second paragraph.
```
becomes equivalent to this:
```gap
#! First paragraph.
#! <P/>
#! Second paragraph.
```
As in LaTeX and MarkDown, multiple empty lines in a row should be coalesced, i.e. this also would be equivalent to the two above examples:
```gap
#! First paragraph.
#!
#!
#!
#! Second paragraph.
```

**Comment by sebasguts** [comment]
Currently we are doing a `<Br/>` for an empty line. So I guess this should be changed to `<P/>`?

**Comment by fingolfin** [comment]
I cannot confirm that. For example, given this input:
```
#! @Chapter Hashmaps
#!
#! A hash map stores key-value pairs and allows efficient lookup of keys
#! by using a hash function.
#! 
#! 
#! New paragraph???
#!
```
I get this output:
```
<Chapter Label="Chapter_Hashmaps">
<Heading>Hashmaps</Heading>

A hash map stores key-value pairs and allows efficient lookup of keys
by using a hash function.
New paragraph???
```

In any case: I do think that `<P/>` would be appropriate, matching LaTeX and Markdown.

**Comment by sebasguts** [comment]
I thought this would happen because of these lines:
https://github.com/gap-packages/AutoDoc/blob/d6ee753056ded0b77276af32b8ec6aea3123ba64/gap/Markdown.gi#L31-L35

But apparently they are never triggered because of
https://github.com/gap-packages/AutoDoc/blob/d6ee753056ded0b77276af32b8ec6aea3123ba64/gap/Parser.gi#L551-L553

So I will fix that and insert a `<P/>` instead of `<Br/>`.
