### ISSUE TITLE
DeclareCategoryCollection causes strange behavior

### ISSUE THREAD

**Issue by gwhitney** [gap-packages/AutoDoc#170]
If you try to run AutoDoc on the following code snippet
```
#! @Chapter Test
#! @Section Some categories
#!  Intro text
DeclareCategory("MyThings", IsObject);
DeclareCategoryCollections("MyThings");
Now here is some text with a bunch of &!$%*!/ weird things in it. You'll
see that it ends up somewhere, shall we say, very unexpected.
```
it produces the following strange-looking error:
```
XML Parse Error: Line [XX] Character 86
Original file: ./crum/_Chapter_Test.xml, line number [YY].
-----------
  <Filt Arg="arg" Name="MyThings" Label="for ;Now here is some text with a bunch of &!$%*!/ weird things in\
 it. You'llsee that it ends up somewhere"/>
                                                                                     ^
-----------
no semicolon in entity reference
```
It appears that AutoDoc is confused and thinks there is another DeclareCategory on the DeclareCategoryCollections line, and then its argument parsing goes haywire. I will shortly post a pull request that adds handling for DeclareCategoryCollections.

**Comment by fingolfin** [comment]
The problem here of course is that we are only looking for the string `DeclareCategory`, but we do not check what is before or after it. Hence we incorrectly "detect" `DeclareCategoryCollection` as `DeclareCategory`.
To fix this more generally, I think we should check that for any matched string, the next character is a non-identifier letter -- in fact, it should be a space of an opening parenthesis...

There are more "Declare*" operations sharing a prefix. Here are all `Declare*` defined in the GAP library; one may see lots of `*Kernel` variants; but also `DeclareSynonymAttr` (documented) and `DeclareCategoryFamily`, `DeclareAttributeSuppCT`, `DeclarePropertySuppCT` (all undocumented).
```
DeclareAttribute
DeclareAttributeKernel
DeclareAttributeSuppCT
DeclareAutoreadableVariables
DeclareCategory
DeclareCategoryCollections
DeclareCategoryFamily
DeclareCategoryKernel
DeclareConstructor
DeclareConstructorKernel
DeclareFilter
DeclareGlobalFunction
DeclareGlobalVariable
DeclareHandlingByNiceBasis
DeclareInfoClass
DeclareObsoleteSynonym
DeclareObsoleteSynonymAttr
DeclareOperation
DeclareOperationKernel
DeclareProperty
DeclarePropertyKernel
DeclarePropertySuppCT
DeclareRepresentation
DeclareRepresentationKernel
DeclareSynonym
DeclareSynonymAttr
DeclareUserPreference
```
