### ISSUE TITLE
AutoDoc generates absolute Paths for external References 

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/AutoDoc#249]
On SmallGrp the documentation provided by the package shows with 
grep doc/ref doc/*.html
entries like
`(<a href="../../../doc/ref/chap39_mj.html#X840A4F937ABF15E1"><span class="RefLink">Reference: RankPGroup</span></a>)`
After running 
gap -q -l 'debian/gaproot;/usr/share/gap' makedoc.g
with
$ ls -l debian/gaproot/pkg/SmallGrp
showing debian/gaproot/pkg/SmallGrp -> ../../..
this becomes
`(<a href="/usr/share/gap/doc/ref/chap39_mj.html#X840A4F937ABF15E1"><span class="RefLink">Reference: RankPGroup</span></a>)`
There should be a way to tell AutoDoc that debian/gaproot and /usr/share/gap will become the same directory or simply to force relative links.

**Comment by fingolfin** [comment]
First off: why do you even regenerate the manuals? This seems like a case of needless self-inflicted pain?

Secondly, it is not AutoDoc which generates these files, it is GAPDoc, and so AutoDoc is constrained by the APIs GAPDoc offers. It's `MakeGAPDocDoc` has an optional `gaproot` parameter which can be used to product relative links. There is an (undocumented) trick in AutoDoc for use by ReleaseTools to override this, by setting the `relativePath` option; you can see how to use it at https://github.com/gap-system/ReleaseTools/blob/b5182b2562f0102e17e95d53ebe88e1b97cf490e/release-gap-package#L387-L391
```gap
if not IsPackageMarkedForLoading("$PKG", "") then
  SetPackagePath("$PKG", ".");
fi;
PushOptions(rec(relativePath:="../../.."));
Read("makedoc.g");
```
However, this is not without caveats: If I recall correctly (but I might not), the relative path really must be valid at the time of compilation, otherwise the paths will be absolute after all.
